package org.sanmarcux.samples.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.*;

import java.util.Date;
import java.util.List;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Actor generated by hbm2java
 *
 * @author pdiaz
 */
@Entity
@Table(name = "actor", catalog = "sakila")
public class Actor implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "actor_id", unique = true, nullable = false)
    private Integer actorId;

    @Column(name = "first_name", nullable = false, length = 45)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 45)
    private String lastName;

    // insertable = false, as on Film.lastUpdate: the column is
    // "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP", so the
    // database fills it. Leaving it insertable made create() send an explicit NULL, which
    // MySQL 5.7 silently rewrote to CURRENT_TIMESTAMP but MySQL 8 rejects outright:
    // explicit_defaults_for_timestamp flipped from 0 to 1 in 8.0.2.
    @Column(name = "last_update", nullable = false, insertable = false, updatable = false)
    private Date lastUpdate;

    // LAZY, not EAGER: ActorDTO exposes only id/firstName/lastName, so eager-loading this
    // meant one extra query per actor on every page of /actors (film_actor joined to film
    // and language), hydrating full film rows that the mapping then threw away.
    // /actors/{id}/films does not read this -- it goes through FilmRepository.findAllByActor.
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "actor")
    private List<FilmActor> filmActors;

    public Actor() {
    }

    public Actor(Integer actorId) {
        this.actorId = actorId;
    }

    public Actor(String firstName, String lastName, Date lastUpdate) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
    }

    public Actor(String firstName, String lastName, Date lastUpdate,
                 List<FilmActor> filmActors) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
        this.filmActors = filmActors;
    }

    public Integer getActorId() {
        return this.actorId;
    }

    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public List<FilmActor> getFilmActors() {
        return this.filmActors;
    }

    public void setFilmActors(List<FilmActor> filmActors) {
        this.filmActors = filmActors;
    }

}
