package org.sanmarcux.samples.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * FilmList generated by hbm2java
 */
@Entity
@Table(name = "film_list", catalog = "sakila")
public class FilmList implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private FilmListId id;

    public FilmList() {
    }

    public FilmList(FilmListId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "fid", column = @Column(name = "FID")),
            @AttributeOverride(name = "title", column = @Column(name = "title")),
            @AttributeOverride(name = "description", column = @Column(name = "description", length = 65535)),
            @AttributeOverride(name = "category", column = @Column(name = "category", nullable = false, length = 25)),
            @AttributeOverride(name = "price", column = @Column(name = "price", precision = 4)),
            @AttributeOverride(name = "length", column = @Column(name = "length")),
            @AttributeOverride(name = "rating", column = @Column(name = "rating", length = 5)),
            @AttributeOverride(name = "actors", column = @Column(name = "actors", length = 341))})
    public FilmListId getId() {
        return this.id;
    }

    public void setId(FilmListId id) {
        this.id = id;
    }

}
