package org.sanmarcux.samples.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FilmCategoryId generated by hbm2java
 */
@Embeddable
public class FilmCategoryId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer filmId;
    private byte categoryId;

    public FilmCategoryId() {
    }

    public FilmCategoryId(Integer filmId, byte categoryId) {
        this.filmId = filmId;
        this.categoryId = categoryId;
    }

    @Column(name = "film_id", nullable = false)
    public Integer getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    @Column(name = "category_id", nullable = false)
    public byte getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(byte categoryId) {
        this.categoryId = categoryId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FilmCategoryId castOther))
            return false;

        // filmId is a boxed Integer (film_id is SMALLINT UNSIGNED, so a primitive short
        // could not hold the top of the range). Compare with equals, not ==, or two ids
        // above the Integer cache would count as different rows.
        return java.util.Objects.equals(this.getFilmId(), castOther.getFilmId())
                && (this.getCategoryId() == castOther.getCategoryId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getFilmId() == null ? 0 : this.getFilmId().hashCode());
        result = 37 * result + this.getCategoryId();
        return result;
    }

}
