package org.sanmarcux.samples.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.io.Serial;

/**
 * FilmActorId generated by hbm2java
 *
 * @author pdiaz
 */
@Embeddable
public class FilmActorId implements java.io.Serializable {

    @Serial
    private static final long serialVersionUID = 1L;
    private int actorId;
    private int filmId;

    public FilmActorId() {
    }

    public FilmActorId(int actorId, int filmId) {
        this.actorId = actorId;
        this.filmId = filmId;
    }

    @Column(name = "actor_id", nullable = false)
    public int getActorId() {
        return this.actorId;
    }

    public void setActorId(int actorId) {
        this.actorId = actorId;
    }

    @Column(name = "film_id", nullable = false)
    public int getFilmId() {
        return this.filmId;
    }

    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FilmActorId castOther))
            return false;

        return (this.getActorId() == castOther.getActorId())
                && (this.getFilmId() == castOther.getFilmId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getActorId();
        result = 37 * result + this.getFilmId();
        return result;
    }

}
