package org.sanmarcux.samples.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "inventory", catalog = "sakila")
public class Inventory implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer inventoryId;
    private Store store;
    private Film film;
    private Date lastUpdate;
    private List<Rental> rentals;

    public Inventory() {
    }

    public Inventory(Store store, Film film, Date lastUpdate) {
        this.store = store;
        this.film = film;
        this.lastUpdate = lastUpdate;
    }

    public Inventory(Store store, Film film, Date lastUpdate,
                     List<Rental> rentals) {
        this.store = store;
        this.film = film;
        this.lastUpdate = lastUpdate;
        this.rentals = rentals;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "inventory_id", unique = true, nullable = false)
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "store_id", nullable = false)
    public Store getStore() {
        return this.store;
    }

    public void setStore(Store store) {
        this.store = store;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "film_id", nullable = false)
    public Film getFilm() {
        return this.film;
    }

    public void setFilm(Film film) {
        this.film = film;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "inventory")
    public List<Rental> getRentals() {
        return this.rentals;
    }

    public void setRentals(List<Rental> rentals) {
        this.rentals = rentals;
    }

}
