package org.sanmarcux.samples.sboot.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * ActorInfo generated by hbm2java
 */
@Entity
@Table(name = "actor_info", catalog = "sakila")
public class ActorInfo implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private ActorInfoId id;

    public ActorInfo() {
    }

    public ActorInfo(ActorInfoId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "actorId", column = @Column(name = "actor_id", nullable = false)),
            @AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 45)),
            @AttributeOverride(name = "lastName", column = @Column(name = "last_name", nullable = false, length = 45)),
            @AttributeOverride(name = "filmInfo", column = @Column(name = "film_info", length = 341))})
    public ActorInfoId getId() {
        return this.id;
    }

    public void setId(ActorInfoId id) {
        this.id = id;
    }

}
