package org.sanmarcux.samples.sboot.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "sakila")
public class City implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Short cityId;
    private Country country;
    private String city;
    private Date lastUpdate;
    private List<Address> addresses;

    public City() {
    }

    public City(Country country, String city, Date lastUpdate) {
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
    }

    public City(Country country, String city, Date lastUpdate, List<Address> addresses) {
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
        this.addresses = addresses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "city_id", unique = true, nullable = false)
    public Short getCityId() {
        return this.cityId;
    }

    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "country_id", nullable = false)
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    @Column(name = "city", nullable = false, length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    public List<Address> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(List<Address> addresses) {
        this.addresses = addresses;
    }

}
