package org.sanmarcux.samples.sboot.sakila.dao.model;

// Generated 20/10/2012 11:23:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "sakila", uniqueConstraints = @UniqueConstraint(columnNames = "manager_staff_id"))
public class Store implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Byte storeId;
    private Staff staff;
    private Address address;
    private Date lastUpdate;
    private List<Inventory> inventories;
    private List<Customer> customers;
    private List<Staff> staffs;

    public Store() {
    }

    public Store(Staff staff, Address address, Date lastUpdate) {
        this.staff = staff;
        this.address = address;
        this.lastUpdate = lastUpdate;
    }

    public Store(Staff staff, Address address, Date lastUpdate,
                 List<Inventory> inventories, List<Customer> customers,
                 List<Staff> staffs) {
        this.staff = staff;
        this.address = address;
        this.lastUpdate = lastUpdate;
        this.inventories = inventories;
        this.customers = customers;
        this.staffs = staffs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "store_id", unique = true, nullable = false)
    public Byte getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Byte storeId) {
        this.storeId = storeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manager_staff_id", unique = true, nullable = false)
    public Staff getStaff() {
        return this.staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id", nullable = false)
    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
    public List<Inventory> getInventories() {
        return this.inventories;
    }

    public void setInventories(List<Inventory> inventories) {
        this.inventories = inventories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
    public List<Customer> getCustomers() {
        return this.customers;
    }

    public void setCustomers(List<Customer> customers) {
        this.customers = customers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
    public List<Staff> getStaffs() {
        return this.staffs;
    }

    public void setStaffs(List<Staff> staffs) {
        this.staffs = staffs;
    }

}
